### ISSUE TITLE
Thanks for opening this issue!

### ISSUE THREAD

**Issue by kushthedude** [kushthedude/Task-Manager#41]
Thanks for opening this issue!

**Comment by kushthedude** [comment]
Hi @crustyy 🥺 🥺 🥺 🥺 🥺

**Comment by crustyy** [comment]
Kaise kara🥺🥺🥺🥺🥺 ooo btw phone se to ho hi jayega laptop ki baat hori

**Comment by kushthedude** [comment]
> Kaise kara🥺🥺🥺🥺 ooo btw phone se to ho hi jayega laptop ki baat hori

Laptop se hi kara hai 😝 🥺

**Comment by kushthedude** [comment]
🤓

**Comment by crustyy** [comment]
🥺🥺🥺🥺🥺🥺kaiseee

**Comment by kushthedude** [comment]
comment box mai `:pleading_face` likho or dekho jadu 😉 @crustyy
